### ISSUE TITLE
Estudo: estudo de conceitos básicos

### ISSUE THREAD

**Issue by RR2M4A** [unb-mds/2024-2-Squad14#1]
## Estudo de Conceitos Básicos

**Descrição:**<br>
Os colaboradores deverão estudar sobre os assuntos a eles atribuídos, a fim de consolidar uma base de conhecimento necessária para a construção do projeto.

Conforme tabela abaixo:

| Responsável                | Tema de Estudo|
|---------------------|---------------------|
| Artur de Camargos   | Critérios de aceitação            |
| André Meyer         | Dívida técnica         |
| Luiz Felipe Bessa   | Burndown        |
| Marco Marques       | Planning Poker      |
| Eduardo Silva Waski | História de Usuário        |
| Marcos Paulo Ribeiro| Artefatos, Rituais, Papéis           |

### Critérios de Aceitação

- [ ] #2

**Comment by ArturDCR** [comment]
Segue o resumo sobre o assunto definido:

Os critérios de aceitação de software são condições que precisam ser atendidas para que o produto seja considerado adequado e pronto para entrega. Eles ajudam a garantir que o software está alinhado com o que foi solicitado pelo cliente e que atende às expectativas definidas no início do projeto. Esses critérios devem ser claros, objetivos e testáveis para evitar mal-entendidos e problemas durante o processo de validação.

Principais aspectos dos critérios de aceitação:
1. Clareza e objetividade: As condições devem ser bem definidas, sem espaço para ambiguidades, para que todos os envolvidos compreendam facilmente.

2. Alinhamento com os requisitos: Os critérios precisam refletir os requisitos iniciais acordados entre o cliente e a equipe de desenvolvimento.

3. Mensurabilidade: Devem ser testáveis, ou seja, é necessário que haja uma maneira objetiva de verificar se o software atende às condições estabelecidas.

4. Abrangência:
   - Funcionalidade: Certificar-se de que o sistema realiza as funções planejadas corretamente.
   - Usabilidade: Garantir que o software é fácil de usar e intuitivo.
   - Desempenho: Avaliar a velocidade, eficiência e consumo de recursos.
   - Confiabilidade: Verificar se o sistema funciona sem falhas críticas.
   - Compatibilidade: Garantir que opera nos ambientes especificados.

5. Cenários de teste: É importante criar cenários reais para verificar se o software cumpre os critérios em situações práticas.

Por que os critérios de aceitação são importantes?
- Alinhamento de expectativas: Eles ajudam a garantir que todos os envolvidos (clientes, usuários e equipe) estão na mesma página.
- Qualidade do produto: Servem como referência para avaliar se o software está pronto para uso.
- Base para testes: Facilitam a definição de testes de aceitação, permitindo identificar problemas antes da entrega final.

Os critérios de aceitação são fundamentais para assegurar que o software atende às necessidades e proporciona confiança no momento da entrega.

Fontes:
- Pressman, Roger S. Engenharia de Software: Uma Abordagem Profissional*. McGraw-Hill.  
- Sommerville, Ian. Software Engineering. Pearson Education.  
- Boehm, Barry. "Verifying and Validating Software Requirements and Design Specifications".  
- Artigos e materiais da comunidade de desenvolvimento de software.

**Comment by lfelipebessa** [comment]
Resumo sobre o Gráfico de Burndown no Desenvolvimento de Software

O gráfico de burndown é uma ferramenta visual que representa o trabalho restante em relação ao tempo estimado para concluí-lo. É amplamente utilizado por equipes ágeis para monitorar o progresso e ajustar o planejamento conforme necessário.

Componentes Principais:

	•	Eixo X (Horizontal): Indica o tempo restante para a conclusão do projeto, geralmente medido em dias.
	•	Eixo Y (Vertical): Representa o esforço remanescente necessário para finalizar o trabalho.

Linhas do Gráfico:

	•	Linha Ideal (Trabalho Estimado):
	•	Mostra a redução uniforme do trabalho em um cenário perfeito.
	•	É geralmente uma linha reta que desce até zero no final do período.
	•	Linha Real (Trabalho Remanescente):
	•	Reflete o progresso real da equipe.
	•	Pode apresentar variações devido a imprevistos ou mudanças no projeto.

Benefícios do Uso:

	•	Monitoramento do Progresso: Permite verificar se a equipe está no ritmo certo para cumprir os prazos.
	•	Planejamento Eficiente: Ajuda a ajustar recursos e cronogramas com base no progresso real.
	•	Insights sobre a Equipe: Oferece visibilidade sobre a eficiência e possíveis obstáculos enfrentados.

Utilizar o gráfico de burndown facilita a comunicação dentro da equipe e com stakeholders, garantindo que todos estejam alinhados quanto ao status do projeto e possibilitando a tomada de decisões informadas.

Fontes:
https://www.atlassian.com/br/agile/tutorials/burndown-charts
https://asana.com/pt/resources/burndown-chart

**Comment by EduardoWaski** [comment]
### Do que se trata que se trata a história de usuário:

História de usuário é em suma, uma descrição breve de uma funcionalidade do ponto de vista de um usuário em questão.

Ela é muito utilizada pois comunica de forma simples as funcionalidades que um usuário final expera de sua aplicação.

- Uma História de usuário geralmente segue o seguinte formato:

   - Como [quem?]
   - Eu quero [o quê?]
   - Para [por quê]
 


- Segue um exemplo:
- 
  > Como cliente do e-commerce, eu quero a funcionalidade de poder parcelar a minha compra para que eu possa ter mais tranquilidade nas contas do mês.
