### ISSUE TITLE
Criação StoryMap

### ISSUE THREAD

**Issue by lfelipebessa** [unb-mds/2024-2-Squad14#4]
## Criação do StoryMap

**Descrição:**<br>
Elaborar um StoryMap para o projeto do dashboard/portal com dados do Diário Oficial do DF. O StoryMap deve organizar as funcionalidades e as jornadas do usuário, permitindo uma visão clara das entregas prioritárias e do roadmap do projeto. Esse processo ajudará a equipe a alinhar expectativas e planejar as etapas de desenvolvimento.

### Critérios de Aceitação

- [x] Critério 1: Activities
- [x] Critério 2: Steps
- [x] Critério 3: Details

### Responsáveis:
André Meyer
Marco Castro

**Comment by AndreMeyerr** [comment]
Feito Colega!
