### ISSUE TITLE
Atualizar GitPages

### ISSUE THREAD

**Issue by lfelipebessa** [unb-mds/2024-2-Squad14#5]
## Atualizar os dados do projeto no gitpage

**Descrição:**<br>
Realizar a atualização das informações do projeto no GitPage, garantindo que estejam consistentes com as entregas mais recentes. A tarefa inclui a verificação e publicação de novos dados, melhorias na organização e correção de possíveis erros nas páginas existentes.

### Critérios de Aceitação

- [x] Critério 1: O conteúdo deve refletir as entregas mais recentes, incluindo mudanças no design, funcionalidades ou descrição do projeto.
- [x] Critério 2: Ter todas as sprints detalhadas, de acordo com o que foi decidido na reunião.

**Comment by EduardoWaski** [comment]
Gitpage atualizada e com as documentações necessarias para a primeira release de MDS.

**Comment by RR2M4A** [comment]
Perfeito.
