### ISSUE TITLE
Definição da Arquitetura do Projeto

### ISSUE THREAD

**Issue by lfelipebessa** [unb-mds/2024-2-Squad14#6]
## Definição da Arquitetura do Projeto

**Descrição:**<br>
Planejar e documentar a arquitetura do projeto do dashboard/portal com dados do Diário Oficial do DF. A tarefa envolve a identificação de componentes-chave, tecnologias utilizadas, organização do sistema e integração entre as partes, garantindo escalabilidade, segurança e manutenção eficiente.

### Critérios de Aceitação

- [ ] Critério 1: Diagrama UML da arquitetura com a linguagem específica.

**Comment by ArturDCR** [comment]
![Classe UML](https://github.com/user-attachments/assets/ec456c27-f2b6-4672-ace6-ab49efcf3db1)

Segue o UML para estruturação do projeto. 
Será usado a arquitetura mvc com o paradigma orientação a objetos.
