### ISSUE TITLE
Criação dos Slides para a Release 1

### ISSUE THREAD

**Issue by lfelipebessa** [unb-mds/2024-2-Squad14#7]
## Criação dos Slides para a Release 1

**Descrição:**<br>
Criação dos slides para apresentação em sala de aula na Release 1.

### Critérios de Aceitação, precisa conter nos slides:

- [x] Critério 1: StoryMap
- [x] Critério 2: Sprints
- [x] Critério 3: Protótipos
- [x] Critério 4: Arquitetura do Projeto

**Comment by RR2M4A** [comment]
Slides finalizados com sucesso.
Eles podem ser encontrados no link abaixo:

https://www.canva.com/design/DAGY5-gkQ1A/I_3_pSZ-CWl_xNeWl8L-zg/edit?utm_content=DAGY5-gkQ1A&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
