### ISSUE TITLE
Visão do Produto na Gitpage

### ISSUE THREAD

**Issue by RR2M4A** [unb-mds/2024-2-Squad14#8]
## Atualização da gitpage com a visão do prodtuo

**Descrição:**<br>
Elabore e adicione na gitpage a visão do produto do software que está sendo desenvolvido.

### Critérios de Aceitação

- [x] Critério 1: A visão do produto deve ser escrita em linguagem clara e objetiva.
- [x] Critério 2: Na visão do produto, deve estar claro o problema que o produto resolve.
- [x] Critério 3: Na visão do produto precisa estar claro qual o público-alvo do produto.
- [x] Critério 4: Será necessário adicionar a visão do produto na gitpage

**Comment by EduardoWaski** [comment]
**Visão de produto** adicionada na gitpage com todos os critérios de aceitação e já feito o deploy da atualização.

**Comment by RR2M4A** [comment]
Perfeito.
